global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "ai_service_main_app"
    metrics_path: "metrics/"
    static_configs:
      - targets:
          - "172.16.50.164:8000" # Assuming main app runs on this port
