# Generated by Django 4.2.13 on 2024-06-10 06:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("authe", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="token",
            name="count_request",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="token",
            name="recent",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="token",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="authe.user"
            ),
        ),
    ]
