# Generated by Django 4.2.13 on 2024-06-16 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_modelai_userpermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='model',
        ),
        migrations.RemoveField(
            model_name='userpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModelAi',
        ),
        migrations.DeleteModel(
            name='Token',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
