# Generated by Django 4.2.13 on 2024-06-17 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0002_adminsettings_aiservice_subscriptionrequest_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminSettings',
        ),
    ]
