# Generated by Django 4.2.13 on 2024-06-17 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0003_delete_adminsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='aiservice',
            name='enterprise_price_per_request',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='aiservice',
            name='monthly_price',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='aiservice',
            name='yearly_price',
            field=models.IntegerField(default=365),
        ),
        migrations.AddField(
            model_name='subscription',
            name='date_ended',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='subscription',
            name='type',
            field=models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly'), ('Enterprise', 'Enterprise')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='active',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Cancelled', 'Cancelled')], max_length=100),
        ),
        migrations.DeleteModel(
            name='SubscriptionRequest',
        ),
        migrations.AddField(
            model_name='billing',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object_detection.aiservice'),
        ),
        migrations.AddField(
            model_name='billing',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='object_detection.subscription'),
        ),
    ]
