# Generated by Django 4.2.13 on 2024-06-18 12:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "object_detection",
            "0004_billing_aiservice_enterprise_price_per_request_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="aiservice",
            name="id_service",
            field=models.IntegerField(null=True),
        ),
    ]
