# Generated by Django 4.2.13 on 2024-06-18 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0005_aiservice_id_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiservice',
            name='id_service',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
