# Generated by Django 4.2.13 on 2024-06-19 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0006_alter_aiservice_id_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesthistory',
            name='subscription',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='object_detection.subscription'),
        ),
    ]
