# Generated by Django 4.2.13 on 2024-06-24 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_detection', '0007_requesthistory_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiservice',
            name='url',
            field=models.CharField(default=1, max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
